{*******************************************************}
{                                                       }
{       Report Manager                                  }
{                                                       }
{       Rpmdconsts                                      }
{                                                       }
{       Resource strings for reportmanager engine and   }
{       designer                                        }
{                                                       }
{       Copyright (c) 1994-2003 Toni Martir             }
{       toni@pala.com                                   }
{                                                       }
{       This file is under the MPL license              }
{       If you enhace this file you must provide        }
{       source code                                     }
{                                                       }
{                                                       }
{*******************************************************}

unit rpmdconsts;

interface

{$I rpconf.inc}

uses SysUtils;

{$IFDEF MSWINDOWS}
const
 C_DIRSEPARATOR='\';
{$ENDIF}
{$IFDEF LINUX}
const
 C_DIRSEPARATOR='/';
{$ENDIF}

const
 RM_VERSION='1.6pre8';

function TranslateStr (index:integer; defvalue:Widestring):WideString;


var
 SRpNoFilename:WideString='No filename assigned';
 SRpErrorFork:WideString='Error forking';
 SRpEnglish:WideString='English';
 SRpSpanish:WideString='Spanish';
 SRpCatalan:WideString='Catalan';
 SRpFrench:WideString='French';
 SRpDirCantBeCreated:WideString='Directory can''t be created: ';
 SRpConfigFileNotExists:WideString='Configuration file missing: ';
 SRpPage:WideString='Page';
 SRpItem:WideString='Item';
 SRpCancel:WideString='Cancel';
 SRpInvalidClipboardFormat:WideString='Invalid clipboard format';
 SRpErrorReadingReport:WideString='Error reading report: ';
 SRpIgnoreError:WideString='Ignore?';
 SRpMainDataset:WideString='Main Dataset';
 SRpNewGroup:WideString='New Group';
 SRpSGroupName:WideString='Group Name';
 SRpGroupAlreadyExists:WideString='Group already exists:';
 SRpNoSpaceToPrint:WideString='No space to print ';
 SRpSection:WideString='Section';
 SRpNothingToPrint:WideString='Nothing to print';

  SRpLastPageReached:WideString='Last page already reached';
  SRPAliasNotExists:WideString='Data alias does not exists: ';
  SRpCopyStreamError:WideString='Error copying stream in metafile image object';
  SRpDriverNotSupported:WideString='Database driver not supported ';
  SrpDriverIBX:WideString='Interbase Express';
  SrpDriverADO:WideString='ADO Express (dbGo)';
  SrpDriverBDE:WideString='Borland Database Engine (BDE)';
  SrpDriverDBX:WideString='SQL Express (DBX)';
  SRpDriverAliasIsNotInterbase:WideString='The dbx driver alias is not Interbase';
  SRpNoDatabase:WideString='No Interbase Database specified';
  SRpSubreportAliasNotFound:WideString='Subreport alias not found:';
  SrpSAggregate:WideString='Aggregate';
  SRpNone:WideString='None';
  SRpGeneral:WideString='General';
  SrpSAgeGroup:WideString='Ag.Group';
  SrpSAgeType:WideString='Ag.Type';
  SrpSum:WideString='Sum';
  SRpMin:WideString='Min';
  SRpMax:WideString='Max';
  SRpAvg:WideString='Average';
  SRpStdDev:WideString='Std.Desv.';
  SrpSIniValue:WideString='Ag.I.Value';
  SrpSIdentifier:WideString='Identifier';
  SRpErrorIdenExpression:WideString='Error expression item no assigned (idenexpression)';
  SRpSHorzLine:WideString='Horz.Line';
  SRpSVertLine:WideString='Vert.Line';
  SRPHorzDesp:WideString='Horz.Desp.';
  SRpInvalidBoolean:WideString='Invalid boolean: ';
  SRpPaperNotFount:WideString='Paper name not found';
  SRpErrorCreatingPaper:WideString='Error creating paper form (privileges?): ';
  SRpSureDeleteSection:WideString='Delete selected section?';
  SRpNoDatasets:WideString='No datasets defined';
  SRpSampleTextToLabels:WideString='Text';
  SRpOnlyAReportOwner:WideString='Only a report can be the owner of :';
  SrpErrorProcesingFileMenu:WideString='Error procesing the File Menu for last saved files';
  SRpRepToTxt1:WideString='reptotxt';
  SRpRepToTxt2:WideString='Converts a report file from report manager (.rep) to a plain file';
  SRpRepToTxt3:WideString='Usage: reptotxt sourcefilename destinationfilename';
  SRpMetaPrint1:WideString='metaprint';
  SRpMetaPrint2:WideString='Prints a metafile report (.rpmf)';
  SRpMetaPrint3:WideString='Usage: metaprint [Options] metafilename';
  SRpMetaPrint4:WideString='Options: -d        Delete the file after printing it';
  SRpMetaPrint5:WideString='         -q        Quiet mode, don''t show progress';
  SRpMetaPrint6:WideString='         -from   n Prints report from page pnum';
  SRpMetaPrint7:WideString='         -to     n Prints report to page pnum';
  SRpMetaPrint8:WideString='         -copies n Prints pnum copies';
  SRpMetaPrint9:WideString='         -collate  Collate the copies';
  SRpTooManyParams:WideString='Too many parameters';
  SRpPrintingFile:WideString='Printing';
  SRpPrinted:WideString='Printed';
  SRpPrintedFileDeleted:WideString='Printed file deleted';
  SRpNoDriverPassedToPrint:WideString='No driver passed to beginprint of TrpReport';
  SRpTxtToRep1:WideString='txttorep';
  SRpTxtToRep2:WideString='Converts a plain file containing object descriptions to a report manager (.rep) file';
  SRpTxtToRep3:WideString='Usage: txttorep sourcefilename destinationfilename';
  SRpPrintRep1:WideString='printrep';
  SRpPrintRep2:WideString='Prints a report manager (.rep) file';
  SRpPrintRep3:WideString='Usage: printrep [Options] reportfilename';
  SRpPrintRep4:WideString='         -q        Quiet mode, don''t show progress';
  SRpPrintRep5:WideString='         -from   n Prints report from page pnum';
  SRpPrintRep6:WideString='         -to     n Prints report to page pnum';
  SRpPrintRep7:WideString='         -copies n Prints pnum copies';
  SRpPrintRep8:WideString='         -collate  Collate the copies';
  SRpPrintPDFRep1:WideString='printreptopdf';
  SRpPrintPDFRep2:WideString='Prints a report manager (.rep) file to a Adobe PDF file';
  SRpPrintPDFRep3:WideString='Usage: printrep [Options] reportfilename pdffilename';
  SRpPrintPDFRep4:WideString='         -q        Quiet mode, don''t show progress';
  SRpPrintPDFRep5:WideString='         -from   n Prints report from page pnum';
  SRpPrintPDFRep6:WideString='         -to     n Prints report to page pnum';
  SRpPrintPDFRep7:WideString='         -copies n Prints pnum copies';
  SRpPrintPDFRep8:WideString='         -u        Generate not compressed pdf';
  SRpPrintPDFRep9:WideString='         -m        Generate Report Metafile Stream format';
  SrpSubReport:WideString='SubReport';
  SRpRepman:WideString='Report manager designer';
  SRpError:WideString='Error';
  SRpOpenSelec:WideString='Opens the selected file';
  SRptReportnotfound:WideString='Report not found';
  SRpMustInstall:WideString='No printers installed, you must install one';
  SRpConverstoolarge:WideString='Conversion overflow';
  SRpErrorMapmode:WideString='Error in mapmode of the device';
  SRpErrorUnitconversion:WideString='Error in unit conversion';
  SRpMinHeight:WideString='Minimal height exceeded';
  SRpMaxWidth:WideString='Maximum height exceeded';
  SRpAssignFunc:WideString='Can not set a value to a function';
  SRpAssignConst:WideString='Can not set a value to a constant';
  SRpAssignfield:WideString='Can not set a value to a field';
  SRpNohelp:WideString='No help available';
  SRpNoaparams:WideString='No parameters';
  SRpNomodel:WideString='No model';
  SRpTrueHelp:WideString='A constant with True value';
  SRpFalseHelp:WideString='A constant with False value';
  SRpFieldHelp:WideString='Database field';
  SRpUpperCase:WideString='Return the string in uppercase';
  SRpPUpperCase:WideString='s is the string to do uppercase';
  SRpLowerCase:WideString='Returns the string in lowercase';
  SRpPLowerCase:WideString='s is the string to do lowercase';
  SRpHourMinSec:WideString='Converts a number to a time string hh:mm:ss';
  SRpPHourMinSec:WideString='H represents hours, idenH is the conversion string '+#10+'for hours, idenM for minutes and '+#10+'idenS for seconds';
  SRpFloatToDateTime:WideString='Converts a float to a datetime type';
  SRpPFloatToDateTime:WideString='n is the number to convert';
  SRpSin:WideString='Returns the sin of an angle';
  SRpPSin:WideString='ang is expressed in radians';
  SRpRound:WideString='Rounds to a multiple of a number.';
  SRpPRound:WideString='num is the number to round and r i the multiplier';
  SRpInt:WideString='Returns the integer part of a number';
  SRpPInt:WideString='num is the number to obtain the int part.';
  SRpStr:WideString='Converts a number to a string';
  SRpPStr:WideString='num is the number to convert';
  SRpVal:WideString='Converts a string to a number';
  SRpPVal:WideString='s is the string to convert';
  SRpTrim:WideString='Returns a string without spaces in right-left sides';
  SRpPtrim:WideString='s is the string to be trimmed';
  SRpLeft:WideString='Returns the left side of a string';
  SRpPLeft:WideString='s is the source string,count is the number of chars to return';
  SRpPos:WideString='Returns the position index of a string inside another string (0 if not found)';
  SRpPPos:WideString='SubStr is the substring to search for';

  SRpAllDriver:WideString='[All]';
  SRpSelectDriver:WideString='You must select a driver first';
  SRpNewConnection:WideString='Create a new connection';
  SRpConnectionName:WideString='Connection name';
  SRpDropConnection:WideString='Drop connection';
  SRpSureDropConnection:WideString='Are you sure you want to drop connection: ';
  SRpVendorLib:WideString='Vendor Library';
  SRpLibraryName:WideString='Library name';
  SRpSelectConnectionFirst:WideString='You must select a connection first';
  SRpConnectionOk:WideString='Test connection passed';
  SRpFieldNotFound:WideString='Field not found: ';
  SRpNotAField:WideString='Not a field: ';
  SRpNotBinary:WideString='Not a binary field: ';
  SRpErrorReadingFromFieldStream:WideString='Error reading from field stream';
  SRpSQrt:WideString='The square of a number';
  SRpPSQRt:WideString='num is the number to square';
  SRpMod:WideString='Returns the module that is the rest of the integer division';
  SRpPMod:WideString='d1 is the dividend d2 is the divisor';
  SRpToday:WideString='Returns today date in datetime data type';
  SRpNow:WideString='Returns today and time in datetime data type';
  SRpTime:WideString='Returns the time in datetime datatype';
  SRpNull:WideString='Null';
  SRpMonthName:WideString='The name of the month in string';
  SRpPMonthName:WideString='d es de date to be decoded';
  SRpEvalText:WideString='Evals an expresion, returns the evaluated result';
  SRpPEvalText:WideString='expr is the expresion to evaluate';
  SRpMonth:WideString='Returns the month number (1-12)';
  SRpPMonth:WideString='d is the date to decode';
  SRpYear:WideString='Returns the year';
  SRpPyear:WideString='d is the date to decode';
  SRpDay:WideString='Returns the day';
  SRpPDay:WideString='d is the date to decode';
  SRpRight:WideString='Returns the right side of a string';
  SRpPRight:WideString='s is the source string and count is the number of characters to copy';
  SRpSubStr:WideString='Returns a substring of a string';
  SRpPSubStr:WideString='cadena is the sorce string, index is the index to copy from '+#10+' and count is the number of characters to copy';
  SRpFormatStr:WideString='Formats a string in diferent ways taking a picture of characters';
  SRpPFormatStr:WideString='Format is the format string: ex.''dd/mm/yyyy'''+#10+' and v is the value to convert to a formated string';
  SRpNumToText:WideString='Text representation of a number';
  SRpPNumToText:WideString='n is the number, f says if it'' female';
  SRpDivisioZero :WideString= 'Division by zero';
  SRpEvalType :WideString= 'Type conversion error';
  SRpInvalidOperation :WideString= 'Invalid operation';
  SRpEvalDescIden :WideString= 'Unknown identifier: ';
  SRpEvalParent :WideString= 'Parentesis error';
  SRpConvertError :WideString= 'Type conversion error';
  SRpIdentifierexpected :WideString= 'Indentifier expected';
  SRpstringexpected :WideString= 'String expected';
  SRpNumberexpected :WideString= 'Number expected';
  SRpOperatorExpected :WideString= 'Operator expected';
  SRpInvalidBinary :WideString= 'Invalid Binary';
  SRpExpected :WideString= 'Expected %s';
  SRpEvalsyntax :WideString= 'Syntax error';
  SRpsetexpression:WideString='Can not set a value to a expression';
  SRpFieldDuplicated :WideString= 'Duplicated field you must use the alias';
  SRpVariabledefined :WideString= 'Variable redefined';
  SRpOperatorSum:WideString='Sum operator';
  SRpOperatorDif:WideString='Substract operator';
  SRpOperatorMul:WideString='Multiply operator';
  SRpOperatorDiv:WideString='Division operator';
  SRpOperatorComp:WideString='Comparison operator';
  SRpOperatorLog:WideString='Logical operator';
  SRpOperatorDec:WideString='Decision operator';
  SRpOperatorDecM:WideString='IIF(condition,action1,action2)';
  SRpOperatorDecP:WideString='Condition is a boolean expresion, if it''s true the '+#10+' first parameter is executed, else the second is executed';
  SRpOperatorSep:WideString='Separator operator';
  SRpOperatorSepP:WideString='Is used to execute more than one expresión, the last is the result';
  SRpErrorOpenImp:WideString='Error opening the printer ';
  SRpPaperexists:WideString='The paper size already exists';
  SRpPrinting:WideString='The printer is already printing';
  SRpDefaultPrinter:WideString='Default printer';
  SRpReportPrinter:WideString='Reporting printer';
  SRpTicketPrinter:WideString='Ticket printer';
  SRpGraphicprinter:WideString='Graphics printer';
  SRpCharacterprinter:WideString='Character based printer';
  SRpReportPrinter2:WideString='Reporting printer 2';
  SRpTicketPrinter2:WideString='Ticket printer 2';
  SRpUserPrinter1:WideString='User printer 1';
  SRpUserPrinter2:WideString='User printer 2';
  SRpUserPrinter3:WideString='User printer 3';
  SRpUserPrinter4:WideString='User printer 4';
  SRpUserPrinter5:WideString='User printer 5';
  SRpUserPrinter6:WideString='User printer 6';
  SRpUserPrinter7:WideString='User printer 7';
  SRpUserPrinter8:WideString='User printer 8';
  SRpUserPrinter9:WideString='User printer 9';
  SRpREmoveElements:WideString='This sections has childs that will be removed.';
  SRpPageHeader:WideString='Page header';
  SRpReportHeader:WideString='Report header';
  SRpGeneralPageHeader:WideString='Global scope';
  SRpGeneralReportHeader:WideString='General report header';
  SRpDetail:WideString='Detail';
  SRpHeader:WideString='Header';
  SRpFooter:WideString='Footer';
  SRpPageFooter:WideString='Page footer';
  SRpReportFooter:WideString='Report footer';
  SRpGroup:WideString='Group';
  SRpMaxGroupsExceded:WideString='Max number of groups execeded';
  SRpSelectGroupToRemove:WideString='Select the group to remove';
  SRpSelectGroup:WideString='Select a group';
  SRpGroupNameError:WideString='The group name is already in use, change it';
  SRpReportChanged:WideString='Report changed. Save the changes before close?';
  SRpErrorWriteSeccion:WideString='Error writing a section';
  SRpErrorReadSeccion:WideString='Error reading a section';
  SRpUntitled:WideString='Untitled';
  SRpSaveAborted:WideString='Save aborted';
  SRpOperationAborted:WideString='Operation aborted';
  SRpFileNameRequired:WideString='File name required to adquire config file';
  SRpAliasExists:WideString='The database alias already exists: ';
  SRPDabaseAliasNotFound:WideString='Database alias not found';
  SRpCircularDatalink:WideString='There is a circular datalink with: ';
  SRPMasterNotFound:WideString='Master dataset not found: ';
  SRpInvalidComponentAssigment:WideString='Error assigning the type must be a valid database';
  SRpNewDatabaseconf:WideString='New database alias configuration';
  SRpEnterTheName:WideString='Enter the alias';
  SRpChangeAliasConf:WideString='Rename the database configuration alias';
  SRpEnterTheNewName:WideString='Enter the new name';
  SRpDatabaseAliasNull:WideString='A database alias cannot be null';
  SRpDatabasenotassined:WideString='There is not database to connect/disconnect in alias';
  SRpConnectionsuccesfull:WideString='Connection Test OK';
  SRpNewaliasDef:WideString='New table/query';
  SRpAliasName:WideString='Alias Name';
  SRpTableAliasExists:WideString='The Alias Name already exists';
  SRpBadSignature:WideString='Bad report metafile signature';
  SRpBadFileHeader:WideString='Bad report metafile file header';
  SrpMtPageSeparatorExpected:WideString='Page separator expected in report metafile';
  SrpMtObjectSeparatorExpected:WideString='Object separator expected in report metafile';
  SrpObjectTypeError:WideString='Object type error in report metafile';
  SrpObjectDataError:WideString='Object data error in report metafile';
  SRpMetaIndexPageOutofBounds:WideString='Index page out of bounds in metafile';
  SRpMetaIndexObjectOutofBounds:WideString='Index object out of bounds in metafile';
  SRpPrintDriverIncorrect:WideString='Incorrect print driver';
  SRpWinGDINotInit:WideString='Report metafile wingdi driver not initialized';
  SRpQtDriverNotInit:WideString='Report metafile qt driver not initialized';
  SRpGDIDriverNotInit:WideString='Report metafile GDI driver not initialized';
  SRPNoSelectedSubreport:WideString='No selected subreport';
  SRPNoSelectedSection:WideString='No selected section';
  SRpGroupNameRequired:WideString='Group name required';
  SRpSubReportNotFound:WideString='Subreport not found';
  SRpSectionNotFound:WideString='Section not found';
  SRpAtLeastOneDetail:WideString='At least one detail must exists in a subreport';
  SRpAtLeastOneSubreport:WideString='At least one subreport must exists in a report';
  SrpNewDataset:WideString='New dataset';
  SrpRenameDataset:WideString='Rename dataset';
  SRpSaveChanges:WideString='Save configuration?';
  SRpParamNotFound:WideString='Parameter not found: ';
  SRpNewParam:WideString='New param';
  SRpParamName:WideString='Name';
  SRpParamNameExists:WideString='Param name already exists';
  SRpRenameParam:WideString='Rename param';
  SRpBold:WideString='Bold';
  SRpUnderline:WideString='Underline';
  SRpItalic:WideString='Italic';
  SRpStrikeOut:WideString='StrikeOut';
  SRpSFontRotation:WideString='F.Rotation';
  SRpSTop:WideString='Top';
  SRpSLeft:WideString='Left';
  SRpSWidth:WideString='Width';
  SRpSHeight:WideString='Height';
  SRpSCurrency:WideString='Currency';
  SRpSString:WideString='String';
  SRpSColor:WideString='Color';
  SRpSInteger:WideString='Integer';
  SRpSWFontName:WideString='WFont Name';
  SRpSLFontName:WideString='LFont Name';
  SRpSType1Font:WideString='PDF Font';
  SrpSFontSize:WideString='Font Size';
  SrpSFontColor:WideString='Font Color';
  SrpSBackColor:WideString='Back Color';
  SrpSFontStyle:WideString='Font Style';
  SrpSTransparent:WideString='Transparent';
  SRpSBool:WideString='Boolean';
  SRpSList:WideString='List';
  SrpSText:WideString='Text';
  SrpSExpression:WideString='Expression';
  SrpSBarcode:WideString='Barcode';
  SrpSCalculatingBarcode:WideString='Error calculating barcode';
  SrpSDisplayFormat:WideString='Display format';
  SRpUnknownType:WideString='(Unknown type)';
  SrpSOnlyOne:WideString='P.Only One';
  SRpSBarcodeType:WideString='Bar type';
  SRpSShowText:WideString='Show Text';
  SRpSChecksum:WideString='Calc.Checksum';
  SRpSModul:WideString='Bar.Modul';
  SRpSRatio:WideString='Bar.Ratio';
  SRpWrongBarcodeType:WideString='Wrong Barcode Type';
  SRpSBSolid:WideString='Solid';
  SRpSBClear:WideString='Clear';
  SRpSBHorizontal:WideString='Horizontal';
  SRpSBVertical:WideString='Vertical';
  SRpSBFDiagonal:WideString='Diagonal A';
  SRpSBBDiagonal:WideString='Diagonal B';
  SRpSBCross:WideString='Cross';
  SRpSBDiagCross:WideString='Diag. Cross';
  SRpSBDense1:WideString='Dense 1';
  SRpSBDense2:WideString='Dense 2';
  SRpSBDense3:WideString='Dense 3';
  SRpSBDense4:WideString='Dense 4';
  SRpSBDense5:WideString='Dense 5';
  SRpSBDense6:WideString='Dense 6';
  SRpSBDense7:WideString='Dense 7';
  SRpSPSolid:WideString='Solid';
  SRpSPDash:WideString='Dash';
  SRpSPDot:WideString='Dot';
  SRpSPDashDot:WideString='Dash-Dot';
  SRpSPDashDotDot:WideString='Dash-Dot-Dot';
  SRpSPClear:WideString='Clear';
  SRpsSCircle:WideString='Circle';
  SRpsSEllipse:WideString='Ellipse';
  SRpsSRectangle:WideString='Rectangle';
  SRpsSRoundRect:WideString='Round Rect';
  SRpsSRoundSquare:WideString='Round Square';
  SRpsSSquare:WideString='Square';
  SRpSAutoExpand:WideString='Auto Expand.';
  SRpSAutoContract:WideString='Auto Contract';
  SRpSAfterPrint:WideString='After print';
  SRpSBeforePrint:WideString='Before print';
  SRpSPrintCondition:WideString='Print condition';
  SRpSGroupExpression:WideString='Group Expression';
  SRPSChangeBool:WideString='Bool Expression';
  SRPSPageRepeat:WideString='Page repeat';
  SRPSBeginPage:WideString='Begin Page';
  SRPSkipPage:WideString='Skip Page';
  SRPAlignBottom:WideString='Align Bottom';
  SRPBottom:WideString='Bottom';
  SRpSRight:WideString='Right';
  SRPAlign:WideString='Align';
  SRpIdentifierAlreadyExists:WideString='Identifier already exists';
  SrpSCutText:WideString='Cut Text';
  SrpSWordwrap:WideString='Word wrap';
  SrpSSingleLine:WideString='Single Line';
  SrpSAlignment:WideString='H.Alignment';
  SrpSVAlignment:WideString='V.Alignment';
  SRpSAlignNone:WideString='None';
  SRpSAlignLeft:WideString='Left';
  SRpSAlignRight:WideString='Right';
  SRpSAlignCenter:WideString='Center';
  SRpSAlignTop:WideString='Top';
  SRpSAlignBottom:WideString='Bottom';
  SRPSDrawCrop:WideString='Crop';
  SRPSDrawStretch:WideString='Strecth';
  SRPSDrawFull:WideString='Full';
  SrpSImage:WideString='Image';
  SRpKbytes:WideString='Kbytes';
  SRpInvalidImageFormat:WideString='Invalid image format';
  SRpPropertyisnotstream:WideString='Property is not a stream: ';
  SrpSShape:WideString='Shape';
  SrpSBrushStyle:WideString='Brush Style';
  SrpSBrushColor:WideString='Brush Color';
  SrpSPenStyle:WideString='Pen Style';
  SrpSPenColor:WideString='Pen Color';
  SrpSPenWIdth:WideString='Pen Width';
  SRpBlackness:WideString='Blackness';
  SRpDstInvert:WideString='DstInvert';
  SRpMergeCopy:WideString='MergeCopy';
  SRpMergePaint:WideString='MergePaint';
  SRpNotSrcCopy:WideString='NotSrcCopy';
  SRpNotSrcErase:WideString='NotSrcErase';
  SRpPatCopy:WideString='PatCopy';
  SRpPatInvert:WideString='PatInvert';
  SRpPatPaint:WideString='PatPaint';
  SRpSrcAnd:WideString='SrcAnd';
  SRpSrcCopy:WideString='SrcCopy';
  SRpSrcErase:WideString='SrcErase';
  SRpSrcInvert:WideString='SrcInvert';
  SRpSrcPaint:WideString='SrcPaint';
  SRpWhiteness:WideString='SrcWhiteness';
  SRpCreateMask:WideString='CreateMask';
  SrpCopyMode:WideString='CopyMode';
  SRpDPIRes:WideString='Resolution(dpi)';
  SRpDrawStyle:WideString='Draw Style';
  SRpDrawTile:WideString='Tile';
  SRpErrorWritingPage:WideString='Error writting metafile page';
  SrpStreamErrorPage:WideString='Error in metafile page format';
  SRpBringToFront:WideString='To Front';
  SRpSendToBack:WideString='To Back';
  SRpInvalidStreaminRpImage:WideString='Invalid stream in TRpImage';
  SRpPropertyNotFound:WideString='Property not found: ';
  SRpPropertyHaveNoListValues:WideString='This property have not a list of values';
  SRpIncorrectComponentForInterface:WideString='Incorrect component type for interface creation';
  SRpPropName:WideString='Property Name';
  SRpPropValue:WideString='Property Value';
  SRpUndefinedPaintInterface:WideString='Undefined paint interface';
  SRpNoDriverName:WideString='No drivername assigned to connection: ';
  SRpIncorrectCalltoDeawGrid:WideString='Incorrect call to DrawBitmapGrid';
  SRpSNotYetImplemented:WideString='Feature not yet implemented';
  SRpNoFileNameProvided:WideString='No filename provided';
  SRpRecordCount:WideString='Record count';
  SRpNoStreamToSaveReport:WideString='No Stream to save Report (TRpDesigner)';
  SRpDocNotInstalled:WideString='Documentation not installed.';
  SRpDocNotInstalled2:WideString='Download it and install in the application directory.';
  SRpDocNotInstalled3:WideString='http://reportman.sourceforge.net';
  SRpSelectAddConnection:WideString='You must select first add/select connection';
  SRpStreamNotValid:WideString='PDF Stream not valid';
  SRpNotPrintingPDF:WideString='Not in pdf printing state';
  SRpInvalidBitmapHeaderSize:WideString='Invalid Bitmap Header Size';
  SRpBadBitmapFileHeader:WideString='Bad bitmap file header';
  SRpBadBitmapStream:WideString='Bad bitmap stream';
  SRpBitMapInfoHeaderBitCount:WideString='Invalid bit depth in bitmap';
  SRpInvalidBitmapPalette:WideString='Invalid bitmap palette';
  SRpBadColorIndex:WideString='Bad color index in bitmap';
  SRpRLECompBitmapPDF:WideString='Compressed RLE bitmaps not supported in PDF Export';
  SRpMonochromeBitmapPDF:WideString='Monochrome bitmaps not supported in PDF Export';
  SRpParamBDENotSupported:WideString='Parameters not supported in BDE Tables';
  SRpPDFFile:WideString='PDF File - compressed';
  SRpPDFFileUn:WideString='PDF File - uncompressed';
  SRpRepMetafile:WideString='Report Metafile';
  SRpRepFile:WideString='Report File';
  SRpAnyFile:WideString='Any File';
  SRpBitmapImages:WideString='Bitmap images';
  SRpUnkownClassForMultiSelect:WideString='Unknown class for multi-select';
  SRpClassNotRegistered:WideString='Class not registered -';
  SRpSampleBarCode:WideString='5449000000996';
  SRpDatasetNotExists:WideString='Dataset not exists';
  SRpDatabaseNotExists:WideString='Database not exists';
  SrpSChartType:WideString='Chart Type';
  SrpSChart:WideString='TRpChart';
  SrpSChangeSerieExp:WideString='Serie Change exp.';
  SrpSChangeSerieBool:WideString='Bool S.Change';
  SrpSCaptionExp:WideString='Caption Exp.';
  SrpSGetValueCondition:WideString='Get V.Cond.';
  SRpIndexOutOfBounds:WideString='Index out of bounds';
  SRpSOblique1:WideString='Oblique1';
  SRpSOblique2:WideString='Oblique2';
  SRpNoFilenameAssignedNotTRpTranslator:WideString='No Filename assigned to TRpTranslator';
  SRpParameter:WideString='Parameter';
  SRpYes:WideString='Yes';
  SRpNo:WideString='No';
  SRpOk:WideString='Ok';
  SRpRetry:WideString='Retry';
  SRpAbort:WideString='Abort';
  SRpIgnore:WideString='Ignore';
  SRpInformation:WideString='Information';
  SRpWarning:WideString='Warning';
  SRpCritical:WideString='Error';
  SRpNotFound:WideString='Not found';
  SRpServerAlreadyRunning:WideString='Report Server already running';
  SRpAuthFailed:WideString='Authorization failed (user name or password incorrect)';
  SRpAuthorized:WideString='Authorization Ok';
  SRpReceivedPacket:WideString='Received Packet:';
  SRpServerStarted:WideString='Server started';
  SRpClientConnected:WideString='Client connected';
  SRpServerStoped:WideString='Server stoped';
  SRpSureDeleteReport:WideString='The selected report will be deleted. Are you sure?';
  SRpGraphicClear:WideString='Clears the graphic data';
  SRpGraphicNew:WideString='Adds data to the graphic';
  SRpPGraphicClear:WideString='Gr is the graphic identifier';
  SRpPGraphicNew:WideString='Gr is the graphic identifier,V is the value, C indications serie change,etiq is the caption of value and caption the serie';
  SRpNoDataAvailableToPrint:WideString='No data available to print';
  SRpPrintOnlyIfDataAvailable:WideString='Print only if data available';
  SRpPasswordConfirmationIncorrect:WideString='Password confirmation incorrect';
  SRpAAliasnameBeAssigned:WideString='A alias name must be specified';
  SRpAPathMustBeAssigned:WideString='A path must be specified';
  SRpAUserNameMustbeAssigned:WideString='A user name must be specified';
  SRpUserorPasswordIncorrect:WideString='User or password incorrect';
  SRpWindowsNTRequired:WideString='Windows NT required to use this feature';
  SRpCannotExecute:WideString='Can not execute';
  SRpServiceStopped:WideString='Stopped';
  SRpServiceStarted:WideString='Started';
  SRpServiceUnInstalled:WideString='Not Installed';
  SRpSExternalpath:WideString='External path';
  SRpGetFieldValue:WideString='Executes a query and returns the first field value';
  SRpPGetFieldValue:WideString='connname is the connection name, query is the sql query to execute';
  SRpChildSubRep:WideString='Child Subreport';
  SRpNewDatabaseInfo:WideString='Select a driver and click add button';
  SRpNewDataInfo:WideString='Click add button, then select a connection and the SQL sentence or other options';
  SRpSExternalData:WideString='External database';
  SRpExternalSectionNotFound:WideString='Error reading external section';
  SRpRecordnotExists:WideString='The record does not exist, do you want to create it?';
  SRpLoadSection:WideString='Do you want to load the section?';
  SRpSInvalidJPEG:WideString='Invalid JPEG/PNG stream';
  SRpSJpegImages:WideString='JPeg images';
  SRpSPNGImages:WideString='PNG images';
  SRpSXPMImages:WideString='XPM images';
  SRpSWMFImages:WideString='WMF Windows Metafile';
  SRpSEMFImages:WideString='EMF Enhaced Metafile';
  SRpSICOImages:WideString='ICO Icons';
  SRpSUnknownType:WideString='Unknown';
  SRpSFloat:WideString='Float';
  SRpSDate:WideString='Date';
  SRpSDateTime:WideString='Date Time';
  SRpSTime:WideString='Time';
  SRpSBoolean:WideString='Boolean';
  SRpSDataType:WideString='Data type';
  SRpSDefault:WideString='Default';
  SRpSDriver:WideString='Driver';
  SRpSChartDriverEngine:WideString='RpChart';
  SRpSChartDriverTeeChart:WideString='TeeChart';
  SRpChartLine:WideString='Line';
  SRpChartBar:WideString='Bar';
  SRpChartPoint:WideString='Point';
  SRpChartHorzBar:WideString='Horz.Bar';
  SRpChartArea:WideString='Area';
  SRpChartPie:WideString='Pie';
  SRpChartArrow:WideString='Arrow';
  SRpChartBubble:WideString='Bubble';
  SRpChartGantt:WideString='Gantt';
  SRPSView3D:WideString='View3D';
  SRPSView3DWalls:WideString='3D Walls';
  SRPSPerspective:WideString='Perspective';
  SRPSElevation:WideString='Elevation';
  SRPSRotation:WideString='Rotation';
  SRPSOrthogonal:WideString='Orthogonal';
  SRPSZoom:WideString='Zoom';
  SRPSHOffset:WideString='H.Offset';
  SRPSVOffset:WideString='V.Offset';
  SRPSTilt:WideString='Tilt';
  SRPSMultibar:WideString='Multibar';
  SRpSNone:WideString='None';
  SRpSSide:WideString='Side';
  SRpSStacked:WideString='Stacked';
  SRpSStacked100:WideString='Stacked100';
  SRpSForcePrint:WideString='Force print';
  SRpSHSkipExpre:WideString='H.Skip.Expre.';
  SRpSVSkipExpre:WideString='V.Skip.Expre.';
  SRpSHRelativeSkip:WideString='H.Relative Skip';
  SRpSVRelativeSkip:WideString='V.Relative Skip';
  SRpSSkipType:WideString='Skip Type';
  SRpSSkipBefore:WideString='Skip Before';
  SRpSSkipAfter:WideString='Skip After';
  SRpSSkipToPage:WideString='S.To Page';
  SRpSPOnlyData:WideString='P.Only data avail.';
  SRpSTwoPassReportNeeded:WideString='Two pass report needed';
  SRpIniNumPage:WideString='Init.PageNum';
  SRpPrintNulls:WideString='Print Nulls';
  SrpSExpressionB:WideString='Expres.Bef.Open';
  SrpSExpressionA:WideString='Expres.Aft.Open';
  SRpSParamSubs:WideString='String Substi.';
  SRpSRightToLeft:WideString='BiDi Mode';
  SRpSBidiNo:WideString='No Bidi';
  SRpSBidiPartial:WideString='Partial Bidi';
  SRpSBidiFull:WideString='Full Bidi';
  SRpMultiPage:WideString='Multi Page';
  SRpDataUnionNotFound:WideString='Data Union not found in Mybase';
  SRpCannotCombine:WideString='Cannot combine-union a dataset to other dataset with fewer field number';
  SRpSParamList:WideString='Value list';
  SRpSParamListDesc:WideString='Strings to show (left) and strings to assign (right)';
  SRpReplaceStr:WideString='Replace a string within a string';
  SRpPReplaceStr:WideString='x Replace a string within a string';
  SRpParseParamsH:WideString='         -paramPARAMNAME=paramvalue  Assign a value to a parameter';
  SrpSClearExpChart:WideString='Clear expression';
  SrpSBoolClearExp:WideString='Bool C.expression';
  // Translate from here
  SRpStreamFormat:WideString='Invalid Stream format';
  SRpZLibNotSupported:WideString='ZLib Streams not supported';
  SRpPreferedFormat:WideString='Prefered save format';
  SRpStreamZLib:WideString='ZLib compressed - binary';
  SRpStreamBinary:WideString='Binary stream';
  SRpStreamText:WideString='Text stream';
  SRpSOptions:WideString='Options';
  SRpSReady:WideString='Ready';
  SRpSsysInfo:WideString='System information';
  SRpSsysInfoH:WideString='Shows system and printer information';
  SRpSHighResolution:WideString='High resolution';
  SRpSMediumResolution:WideString='Medium resolution';
  SRpSLowResolution:WideString='Low resolution';
  SRpSDraftResolution:WideString='Draft resolution';
  SRpSColorPrinting:WideString='Color printing';
  SRpSMonoPrinting:WideString='Monochrome printing';
  SRSPlotter:WideString='Plotter, vector printer';
  SRSRasterDisplay:WideString='Raster display';
  SRSRasterPrinter:WideString='Raster printer';
  SRSRasterCamera:WideString='Raster camera';
  SRSCharStream:WideString='Character stream';
  SRSDisplayFile:WideString='Display file';
  SRpSMetafile:WideString='Windows Metafile';
  SRpSPolyline:WideString='Polyline';
  SRpSMarker:WideString='Marker';
  SRpSPolyMarker:WideString='Multiple Marker';
  SRpSWideCap:WideString='Wide capability';
  SRpSSTyledCap:WideString='Styled capability';
  SRpSWideSTyledCap:WideString='Wide styled capability';
  SRpSInteriorsCap:WideString='Interiors capability';
  SRpSPolygon:WideString='Polygon capability';
  SRpSRectanglecap:WideString='Rectangle capability';
  SRpSWindPolygon:WideString='Winding-fill cap.';
  SRpSSCANLINE:WideString='Scan line cap.';
  SRpSCircleCap:WideString='Circle cap.';
  SRpSPiecap:WideString='Pie wedges cap.';
  SRpSCHordCap:WideString='Chord arcs cap.';
  SRpSEllipses:WideString='Ellipses cap.';
  SRpSRoundRectCap:WideString='Round rect.cap.';
  SRpSBandingRequired:WideString='Banding required';
  SRpSBitmapTransfer:WideString='Bitmap transfer cap.';
  SRpSBitmapTransfer64:WideString='B.transfer>64K cap.';
  SRpSDIBTransfer:WideString='Dev.Ind.Bitmap support';
  SRpSDIBDevTransfer:WideString='DIBToDevice support';
  SRpSFloodFillcap:WideString='Flood Fill cap.';
  SRpSGDI20Out:WideString='Win.GDI 2.0 support';
  SRPSPaletteDev:WideString='Palette device';
  SRpSScalingCap:WideString='Scaling cap.';
  SRpSStretchCap:WideString='Stretch blitter cap.';
  SRpSStretchDIBCap:WideString='Stretch DIB cap.';
  SRpSCharOutput:WideString='Character precision cap.';
  SRpSCharStroke:WideString='Character stroke precision';
  SRpSClipStroke:WideString='Clip stroke precision';
  SRpS90Rotation:WideString='90 Degree Rotation cap.';
  SRpSAnyRotation:WideString='Any Degree Rotation cap.';
  SRpSScaleXY:WideString='Scale X/Y direction cap.';
  SRpSDoubleChar:WideString='Double scale chars cap.';
  SRpSIntegerScale:WideString='Interger scale only cap.';
  SRpSAnyrScale:WideString='Exact char scaling cap.';
  SRpSDoubleWeight:WideString='Double weight cap.';
  SRpRasterFonts:WideString='Raster fonts';
  SRpVectorFonts:WideString='Vector fonts';
  SRpNobitBlockScroll:WideString='No bitblock scroll';
  SRpExcelFile:WideString='Excel file';
  SRpExcelNotSupported:WideString='Excel not supported';
  SRpPrintConditionHint:WideString='Boolean expression, if evaluated to false this component/section will not print, this is a multiline hint it spans auto across some lines because it does not fit in screen, well may be if a high resolution is selected this hint will be visible in only ';
  SRpFieldsFileNotDefined:WideString='Fields file not defined';
  SRpSMemo:WideString='Memo';
  SRpSInvReportHandle:WideString='Invalid report handle';


implementation

uses rptranslator;

var
 atrans:TRpTranslator;

function TranslateStr(index:integer;defvalue:Widestring):WideString;
begin
 if Not Assigned(atrans) then
 begin
  atrans:=TRpTranslator.Create(nil);
  atrans.Filename:='reportmanres';
  atrans.Active:=true;
 end;
 Result:=atrans.LoadString(index,defvalue);
end;

procedure TranslateVar(index:integer;var astring:Widestring);
begin
 if Not Assigned(atrans) then
 begin
  atrans:=TRpTranslator.Create(nil);
  atrans.Filename:='reportmanres';
  atrans.Active:=true;
 end;
 astring:=atrans.LoadString(index,astring);
end;

procedure ConvertAllStrings;
begin
 TranslateVar(95,SRpSDefault);
 TranslateVar(262,SRpNoFilename);
 TranslateVar(263,SRpErrorFork);
 TranslateVar(264,SRpEnglish);
 TranslateVar(265,SRpSpanish);
 TranslateVar(266,SRpCatalan);
 TranslateVar(267,SRpDirCantBeCreated);
 TranslateVar(268,SRpConfigFileNotExists);
 TranslateVar(269,SRpPage);
 TranslateVar(270,SRpItem);
 TranslateVar(271,SRpCancel);
 TranslateVar(272,SRpInvalidClipboardFormat);
 TranslateVar(273,SRpErrorReadingReport);
 TranslateVar(274,SRpIgnoreError);
 TranslateVar(275,SRpMainDataset);
 TranslateVar(276,SRpNewGroup);
 TranslateVar(277,SRpSGroupName);
 TranslateVar(278,SRpGroupAlreadyExists);
 TranslateVar(279,SRpNoSpaceToPrint);
 TranslateVar(280,SRpSection);
 TranslateVar(281,SRpNothingToPrint);
 TranslateVar(282,SRpLastPageReached);
 TranslateVar(283,SRPAliasNotExists);
 TranslateVar(284,SRpCopyStreamError);
 TranslateVar(285,SRpDriverNotSupported);
 TranslateVar(286,SrpDriverIBX);
 TranslateVar(287,SrpDriverADO);
 TranslateVar(288,SrpDriverBDE);
 TranslateVar(289,SrpDriverDBX);
 TranslateVar(290,SRpDriverAliasIsNotInterbase);
 TranslateVar(291,SRpNoDatabase);
 TranslateVar(292,SRpSubreportAliasNotFound);
 TranslateVar(293,SrpSAggregate);
 TranslateVar(294,SRpNone);
 TranslateVar(295,SRpGeneral);
 TranslateVar(296,SrpSAgeGroup);
 TranslateVar(297,SrpSAgeType);
 TranslateVar(298,SrpSum);
 TranslateVar(299,SRpMin);
 TranslateVar(300,SRpMax);
 TranslateVar(301,SRpAvg);
 TranslateVar(302,SRpStdDev);
 TranslateVar(303,SrpSIniValue);
 TranslateVar(304,SrpSIdentifier);
 TranslateVar(305,SRpErrorIdenExpression);
 TranslateVar(306,SRpSHorzLine);
 TranslateVar(307,SRpSVertLine);
 TranslateVar(308,SRPHorzDesp);
 TranslateVar(309,SRpInvalidBoolean);
 TranslateVar(310,SRpPaperNotFount);
 TranslateVar(311,SRpErrorCreatingPaper);
 TranslateVar(312,SRpSureDeleteSection);
 TranslateVar(313,SRpNoDatasets);
 TranslateVar(314,SRpSampleTextToLabels);
 TranslateVar(315,SRpOnlyAReportOwner);
 TranslateVar(316,SrpErrorProcesingFileMenu);
 TranslateVar(317,SRpRepToTxt1);
 TranslateVar(318,SRpRepToTxt2);
 TranslateVar(319,SRpRepToTxt3);
 TranslateVar(320,SRpMetaPrint1);
 TranslateVar(321,SRpMetaPrint2);
 TranslateVar(322,SRpMetaPrint3);
 TranslateVar(323,SRpMetaPrint4);
 TranslateVar(324,SRpMetaPrint5);
 TranslateVar(325,SRpMetaPrint6);
 TranslateVar(326,SRpMetaPrint7);
 TranslateVar(327,SRpMetaPrint8);
 TranslateVar(328,SRpMetaPrint9);
 TranslateVar(329,SRpTooManyParams);
 TranslateVar(330,SRpPrintingFile);
 TranslateVar(331,SRpPrinted);
 TranslateVar(332,SRpPrintedFileDeleted);
 TranslateVar(333,SRpNoDriverPassedToPrint);
 TranslateVar(334,SRpTxtToRep1);
 TranslateVar(335,SRpTxtToRep2);
 TranslateVar(336,SRpTxtToRep3);
 TranslateVar(337,SRpPrintRep1);
 TranslateVar(338,SRpPrintRep2);
 TranslateVar(339,SRpPrintRep3);
 TranslateVar(340,SRpPrintRep4);
 TranslateVar(341,SRpPrintRep5);
 TranslateVar(342,SRpPrintRep6);
 TranslateVar(343,SRpPrintRep7);
 TranslateVar(344,SRpPrintRep8);
 TranslateVar(345,SRpPrintPDFRep1);
 TranslateVar(346,SRpPrintPDFRep2);
 TranslateVar(347,SRpPrintPDFRep3);
 TranslateVar(348,SRpPrintPDFRep4);
 TranslateVar(349,SRpPrintPDFRep5);
 TranslateVar(350,SRpPrintPDFRep6);
 TranslateVar(351,SRpPrintPDFRep7);
 TranslateVar(352,SRpPrintPDFRep8);
 TranslateVar(353,SrpSubReport);
 TranslateVar(354,SRpRepman);
 TranslateVar(355,SRpError);
 TranslateVar(356,SRpOpenSelec);
 TranslateVar(357,SRptReportnotfound);
 TranslateVar(358,SRpMustInstall);
 TranslateVar(359,SRpConverstoolarge);
 TranslateVar(360,SRpErrorMapmode);
 TranslateVar(361,SRpErrorUnitconversion);
 TranslateVar(362,SRpMinHeight);
 TranslateVar(363,SRpMaxWidth);
 TranslateVar(364,SRpAssignFunc);
 TranslateVar(365,SRpAssignConst);
 TranslateVar(366,SRpAssignfield);
 TranslateVar(367,SRpNohelp);
 TranslateVar(368,SRpNoaparams);
 TranslateVar(369,SRpNomodel);
 TranslateVar(370,SRpTrueHelp);
 TranslateVar(371,SRpFalseHelp);
 TranslateVar(372,SRpFieldHelp);
 TranslateVar(373,SRpUpperCase);
 TranslateVar(374,SRpPUpperCase);
 TranslateVar(375,SRpLowerCase);
 TranslateVar(376,SRpPLowerCase);
 TranslateVar(377,SRpHourMinSec);
 TranslateVar(378,SRpPHourMinSec);
 TranslateVar(379,SRpFloatToDateTime);
 TranslateVar(380,SRpPFloatToDateTime);
 TranslateVar(381,SRpSin);
 TranslateVar(382,SRpPSin);
 TranslateVar(383,SRpRound);
 TranslateVar(384,SRpPRound);
 TranslateVar(385,SRpInt);
 TranslateVar(386,SRpPInt);
 TranslateVar(387,SRpStr);
 TranslateVar(388,SRpPStr);
 TranslateVar(389,SRpVal);
 TranslateVar(390,SRpPVal);
 TranslateVar(391,SRpTrim);
 TranslateVar(392,SRpPtrim);
 TranslateVar(393,SRpLeft);
 TranslateVar(394,SRpPLeft);
 TranslateVar(395,SRpPos);
 TranslateVar(396,SRpPPos);

 TranslateVar(397,SRpAllDriver);
 TranslateVar(398,SRpSelectDriver);
 TranslateVar(399,SRpNewConnection);
 TranslateVar(400,SRpConnectionName);
 TranslateVar(401,SRpDropConnection);
 TranslateVar(402,SRpSureDropConnection);
 TranslateVar(403,SRpVendorLib);
 TranslateVar(404,SRpLibraryName);
 TranslateVar(405,SRpSelectConnectionFirst);
 TranslateVar(406,SRpConnectionOk);
 TranslateVar(407,SRpFieldNotFound);
 TranslateVar(408,SRpNotAField);
 TranslateVar(409,SRpNotBinary);
 TranslateVar(410,SRpErrorReadingFromFieldStream);
 TranslateVar(411,SRpSQrt);
 TranslateVar(412,SRpPSQRt);
 TranslateVar(413,SRpMod);
 TranslateVar(414,SRpPMod);
 TranslateVar(415,SRpToday);
 TranslateVar(416,SRpNow);
 TranslateVar(417,SRpTime);
 TranslateVar(418,SRpNull);
 TranslateVar(419,SRpMonthName);
 TranslateVar(420,SRpPMonthName);
 TranslateVar(421,SRpEvalText);
 TranslateVar(422,SRpPEvalText);
 TranslateVar(423,SRpMonth);
 TranslateVar(424,SRpPMonth);
 TranslateVar(425,SRpYear);
 TranslateVar(426,SRpPyear);
 TranslateVar(427,SRpDay);
 TranslateVar(428,SRpPDay);
 TranslateVar(429,SRpRight);
 TranslateVar(430,SRpPRight);
 TranslateVar(431,SRpSubStr);
 TranslateVar(432,SRpPSubStr);
 TranslateVar(433,SRpFormatStr);
 TranslateVar(434,SRpPFormatStr);
 TranslateVar(435,SRpNumToText);
 TranslateVar(436,SRpPNumToText);
 TranslateVar(437,SRpDivisioZero);
 TranslateVar(438,SRpEvalType);
 TranslateVar(439,SRpInvalidOperation);
 TranslateVar(440,SRpEvalDescIden);
 TranslateVar(441,SRpEvalParent);
 TranslateVar(442,SRpConvertError);
 TranslateVar(443,SRpIdentifierexpected);
 TranslateVar(444,SRpstringexpected);
 TranslateVar(445,SRpNumberexpected);
 TranslateVar(446,SRpOperatorExpected);
 TranslateVar(447,SRpInvalidBinary);
 TranslateVar(448,SRpExpected);
 TranslateVar(449,SRpEvalsyntax);
 TranslateVar(450,SRpsetexpression);
 TranslateVar(451,SRpFieldDuplicated);
 TranslateVar(452,SRpVariabledefined);
 TranslateVar(453,SRpOperatorSum);
 TranslateVar(454,SRpOperatorDif);
 TranslateVar(455,SRpOperatorMul);
 TranslateVar(456,SRpOperatorDiv);
 TranslateVar(457,SRpOperatorComp);
 TranslateVar(458,SRpOperatorLog);
 TranslateVar(459,SRpOperatorDec);
 TranslateVar(460,SRpOperatorDecM);
 TranslateVar(461,SRpOperatorDecP);
 TranslateVar(462,SRpOperatorSep);
 TranslateVar(463,SRpOperatorSepP);
 TranslateVar(464,SRpErrorOpenImp);
 TranslateVar(465,SRpPaperexists);
 TranslateVar(466,SRpPrinting);
 TranslateVar(467,SRpDefaultPrinter);
 TranslateVar(468,SRpReportPrinter);
 TranslateVar(469,SRpTicketPrinter);
 TranslateVar(470,SRpGraphicprinter);
 TranslateVar(471,SRpCharacterprinter);
 TranslateVar(472,SRpReportPrinter2);
 TranslateVar(473,SRpTicketPrinter2);
 TranslateVar(474,SRpUserPrinter1);
 TranslateVar(475,SRpUserPrinter2);
 TranslateVar(476,SRpUserPrinter3);
 TranslateVar(477,SRpUserPrinter4);
 TranslateVar(478,SRpUserPrinter5);
 TranslateVar(479,SRpUserPrinter6);
 TranslateVar(480,SRpUserPrinter7);
 TranslateVar(481,SRpUserPrinter8);
 TranslateVar(482,SRpUserPrinter9);
 TranslateVar(483,SRpREmoveElements);
 TranslateVar(484,SRpPageHeader);
 TranslateVar(485,SRpReportHeader);
 TranslateVar(486,SRpGeneralPageHeader);
 TranslateVar(487,SRpGeneralReportHeader);
 TranslateVar(488,SRpDetail);
 TranslateVar(489,SRpHeader);
 TranslateVar(490,SRpFooter);
 TranslateVar(491,SRpPageFooter);
 TranslateVar(492,SRpReportFooter);
 TranslateVar(493,SRpGroup);
 TranslateVar(494,SRpMaxGroupsExceded);
 TranslateVar(495,SRpSelectGroupToRemove);
 TranslateVar(496,SRpSelectGroup);
 TranslateVar(497,SRpGroupNameError);
 TranslateVar(498,SRpReportChanged);
 TranslateVar(499,SRpErrorWriteSeccion);
 TranslateVar(500,SRpErrorReadSeccion);
 TranslateVar(501,SRpUntitled);
 TranslateVar(502,SRpSaveAborted);
 TranslateVar(503,SRpOperationAborted);
 TranslateVar(504,SRpFileNameRequired);
 TranslateVar(505,SRpAliasExists);
 TranslateVar(506,SRPDabaseAliasNotFound);
 TranslateVar(507,SRpCircularDatalink);
 TranslateVar(508,SRPMasterNotFound);
 TranslateVar(509,SRpInvalidComponentAssigment);
 TranslateVar(510,SRpNewDatabaseconf);
 TranslateVar(511,SRpEnterTheName);
 TranslateVar(512,SRpChangeAliasConf);
 TranslateVar(513,SRpEnterTheNewName);
 TranslateVar(514,SRpDatabaseAliasNull);
 TranslateVar(515,SRpDatabasenotassined);
 TranslateVar(516,SRpConnectionsuccesfull);
 TranslateVar(517,SRpNewaliasDef);
 TranslateVar(518,SRpAliasName);
 TranslateVar(519,SRpTableAliasExists);
 TranslateVar(520,SRpBadSignature);
 TranslateVar(521,SRpBadFileHeader);
 TranslateVar(522,SrpMtPageSeparatorExpected);
 TranslateVar(523,SrpMtObjectSeparatorExpected);
 TranslateVar(524,SrpObjectTypeError);
 TranslateVar(525,SrpObjectDataError);
 TranslateVar(526,SRpMetaIndexPageOutofBounds);
 TranslateVar(527,SRpMetaIndexObjectOutofBounds);
 TranslateVar(528,SRpPrintDriverIncorrect);
 TranslateVar(529,SRpWinGDINotInit);
 TranslateVar(530,SRpQtDriverNotInit);
 TranslateVar(531,SRpGDIDriverNotInit);
 TranslateVar(532,SRPNoSelectedSubreport);
 TranslateVar(533,SRPNoSelectedSection);
 TranslateVar(534,SRpGroupNameRequired);
 TranslateVar(535,SRpSubReportNotFound);
 TranslateVar(536,SRpSectionNotFound);
 TranslateVar(537,SRpAtLeastOneDetail);
 TranslateVar(538,SRpAtLeastOneSubreport);
 TranslateVar(539,SrpNewDataset);
 TranslateVar(540,SrpRenameDataset);
 TranslateVar(541,SRpSaveChanges);
 TranslateVar(542,SRpParamNotFound);
 TranslateVar(543,SRpNewParam);
 TranslateVar(544,SRpParamName);
 TranslateVar(545,SRpParamNameExists);
 TranslateVar(546,SRpRenameParam);
 TranslateVar(547,SRpBold);
 TranslateVar(548,SRpUnderline);
 TranslateVar(549,SRpItalic);
 TranslateVar(550,SRpStrikeOut);
 TranslateVar(551,SRpSFontRotation);
 TranslateVar(552,SRpSTop);
 TranslateVar(553,SRpSLeft);
 TranslateVar(554,SRpSWidth);
 TranslateVar(555,SRpSHeight);
 TranslateVar(556,SRpSCurrency);
 TranslateVar(557,SRpSString);
 TranslateVar(558,SRpSColor);
 TranslateVar(559,SRpSInteger);
 TranslateVar(560,SRpSWFontName);
 TranslateVar(561,SRpSLFontName);
 TranslateVar(562,SRpSType1Font);
 TranslateVar(563,SrpSFontSize);
 TranslateVar(564,SrpSFontColor);
 TranslateVar(565,SrpSBackColor);
 TranslateVar(566,SrpSFontStyle);
 TranslateVar(567,SrpSTransparent);
 TranslateVar(568,SRpSBool);
 TranslateVar(569,SRpSList);
 TranslateVar(570,SrpSText);
 TranslateVar(571,SrpSExpression);
 TranslateVar(572,SrpSBarcode);
 TranslateVar(573,SrpSCalculatingBarcode);
 TranslateVar(574,SrpSDisplayFormat);
 TranslateVar(575,SRpUnknownType);
 TranslateVar(576,SrpSOnlyOne);
 TranslateVar(577,SRpSBarcodeType);
 TranslateVar(578,SRpSShowText);
 TranslateVar(579,SRpSChecksum);
 TranslateVar(580,SRpSModul);
 TranslateVar(581,SRpSRatio);
 TranslateVar(582,SRpWrongBarcodeType);
 TranslateVar(583,SRpSBSolid);
 TranslateVar(584,SRpSBClear);
 TranslateVar(585,SRpSBHorizontal);
 TranslateVar(586,SRpSBVertical);
 TranslateVar(587,SRpSBFDiagonal);
 TranslateVar(588,SRpSBBDiagonal);
 TranslateVar(589,SRpSBCross);
 TranslateVar(590,SRpSBDiagCross);
 TranslateVar(591,SRpSBDense1);
 TranslateVar(592,SRpSBDense2);
 TranslateVar(593,SRpSBDense3);
 TranslateVar(594,SRpSBDense4);
 TranslateVar(595,SRpSBDense5);
 TranslateVar(596,SRpSBDense6);
 TranslateVar(597,SRpSBDense7);
 TranslateVar(598,SRpSPSolid);
 TranslateVar(599,SRpSPDash);
 TranslateVar(600,SRpSPDot);
 TranslateVar(601,SRpSPDashDot);
 TranslateVar(602,SRpSPDashDotDot);
 TranslateVar(603,SRpSPClear);
 TranslateVar(604,SRpsSCircle);
 TranslateVar(605,SRpsSEllipse);
 TranslateVar(606,SRpsSRectangle);
 TranslateVar(607,SRpsSRoundRect);
 TranslateVar(608,SRpsSRoundSquare);
 TranslateVar(609,SRpsSSquare);
 TranslateVar(610,SRpSAutoExpand);
 TranslateVar(611,SRpSAutoContract);
 TranslateVar(612,SRpSAfterPrint);
 TranslateVar(613,SRpSBeforePrint);
 TranslateVar(614,SRpSPrintCondition);
 TranslateVar(615,SRpSGroupExpression);
 TranslateVar(616,SRPSChangeBool);
 TranslateVar(617,SRPSPageRepeat);
 TranslateVar(618,SRPSBeginPage);
 TranslateVar(619,SRPSkipPage);
 TranslateVar(620,SRPAlignBottom);
 TranslateVar(621,SRPBottom);
 TranslateVar(622,SRpSRight);
 TranslateVar(623,SRPAlign);
 TranslateVar(624,SRpIdentifierAlreadyExists);
 TranslateVar(625,SrpSCutText);
 TranslateVar(626,SrpSWordwrap);
 TranslateVar(627,SrpSSingleLine);
 TranslateVar(628,SrpSAlignment);
 TranslateVar(629,SrpSVAlignment);
 TranslateVar(630,SRpSAlignNone);
 TranslateVar(631,SRpSAlignLeft);
 TranslateVar(632,SRpSAlignRight);
 TranslateVar(633,SRpSAlignCenter);
 TranslateVar(634,SRpSAlignTop);
 TranslateVar(635,SRpSAlignBottom);
 TranslateVar(636,SRPSDrawCrop);
 TranslateVar(637,SRPSDrawStretch);
 TranslateVar(638,SRPSDrawFull);
 TranslateVar(639,SrpSImage);
 TranslateVar(640,SRpKbytes);
 TranslateVar(641,SRpInvalidImageFormat);
 TranslateVar(642,SRpPropertyisnotstream);
 TranslateVar(643,SrpSShape);
 TranslateVar(644,SrpSBrushStyle);
 TranslateVar(645,SrpSBrushColor);
 TranslateVar(646,SrpSPenStyle);
 TranslateVar(647,SrpSPenColor);
 TranslateVar(648,SrpSPenWIdth);
 TranslateVar(649,SRpBlackness);
 TranslateVar(650,SRpDstInvert);
 TranslateVar(651,SRpMergeCopy);
 TranslateVar(652,SRpMergePaint);
 TranslateVar(653,SRpNotSrcCopy);
 TranslateVar(654,SRpNotSrcErase);
 TranslateVar(655,SRpPatCopy);
 TranslateVar(656,SRpPatInvert);
 TranslateVar(657,SRpPatPaint);
 TranslateVar(658,SRpSrcAnd);
 TranslateVar(659,SRpSrcCopy);
 TranslateVar(660,SRpSrcErase);
 TranslateVar(661,SRpSrcInvert);
 TranslateVar(662,SRpSrcPaint);
 TranslateVar(663,SRpWhiteness);
 TranslateVar(664,SRpCreateMask);
 TranslateVar(665,SrpCopyMode);
 TranslateVar(666,SRpDPIRes);
 TranslateVar(667,SRpDrawStyle);
 TranslateVar(668,SRpDrawTile);
 TranslateVar(669,SRpErrorWritingPage);
 TranslateVar(670,SrpStreamErrorPage);
 TranslateVar(671,SRpBringToFront);
 TranslateVar(672,SRpSendToBack);
 TranslateVar(673,SRpInvalidStreaminRpImage);
 TranslateVar(674,SRpPropertyNotFound);
 TranslateVar(675,SRpPropertyHaveNoListValues);
 TranslateVar(676,SRpIncorrectComponentForInterface);
 TranslateVar(677,SRpPropName);
 TranslateVar(678,SRpPropValue);
 TranslateVar(679,SRpUndefinedPaintInterface);
 TranslateVar(680,SRpNoDriverName);
 TranslateVar(681,SRpIncorrectCalltoDeawGrid);
 TranslateVar(682,SRpSNotYetImplemented);
 TranslateVar(683,SRpNoFileNameProvided);
 TranslateVar(684,SRpRecordCount);
 TranslateVar(685,SRpNoStreamToSaveReport);
 TranslateVar(686,SRpDocNotInstalled);
 TranslateVar(687,SRpDocNotInstalled2);
 TranslateVar(688,SRpDocNotInstalled3);
 TranslateVar(689,SRpSelectAddConnection);
 TranslateVar(690,SRpStreamNotValid);
 TranslateVar(691,SRpNotPrintingPDF);
 TranslateVar(692,SRpInvalidBitmapHeaderSize);
 TranslateVar(693,SRpBadBitmapFileHeader);
 TranslateVar(694,SRpBadBitmapStream);
 TranslateVar(695,SRpBitMapInfoHeaderBitCount);
 TranslateVar(696,SRpInvalidBitmapPalette);
 TranslateVar(697,SRpBadColorIndex);
 TranslateVar(698,SRpRLECompBitmapPDF);
 TranslateVar(699,SRpMonochromeBitmapPDF);
 TranslateVar(700,SRpParamBDENotSupported);
 TranslateVar(701,SRpPDFFile);
 TranslateVar(702,SRpPDFFileUn);
 TranslateVar(703,SRpRepMetafile);
 TranslateVar(704,SRpRepFile);
 TranslateVar(705,SRpAnyFile);
 TranslateVar(706,SRpBitmapImages);
 TranslateVar(707,SRpUnkownClassForMultiSelect);
 TranslateVar(708,SRpClassNotRegistered);
 TranslateVar(709,SRpSampleBarCode);
 TranslateVar(710,SRpDatasetNotExists);
 TranslateVar(711,SRpDatabaseNotExists);
 TranslateVar(712,SrpSChartType);
 TranslateVar(713,SrpSChart);
 TranslateVar(714,SrpSChangeSerieExp);
 TranslateVar(715,SrpSChangeSerieBool);
 TranslateVar(716,SrpSCaptionExp);
 TranslateVar(717,SrpSGetValueCondition);
 TranslateVar(718,SRpIndexOutOfBounds);
 TranslateVar(719,SRpSOblique1);
 TranslateVar(720,SRpSOblique2);
 TranslateVar(721,SRpNoFilenameAssignedNotTRpTranslator);
 TranslateVar(722,SRpParameter);
 TranslateVar(723,SRpYes);
 TranslateVar(724,SRpNo);
 TranslateVar(93,SRpOk);
 TranslateVar(725,SRpRetry);
 TranslateVar(726,SRpAbort);
 TranslateVar(727,SRpIgnore);
 TranslateVar(728,SrpInformation);
 TranslateVar(729,SrpWarning);
 TranslateVar(730,SRpError);
 TranslateVar(731,SRpNotFound);
 TranslateVar(768,SRpServerAlreadyRunning);
 TranslateVar(771,SRpAuthFailed);
 TranslateVar(772,SRpAuthorized);
 TranslateVar(776,SRpReceivedPacket);
 TranslateVar(787,SRpServerStarted);
 TranslateVar(788,SRpClientConnected);
 TranslateVar(789,SRpServerStoped);
 TranslateVar(794,SRpSureDeleteReport);
 TranslateVar(795,SRpGraphicClear);
 TranslateVar(796,SRpGraphicNew);
 TranslateVar(797,SRpPGraphicClear);
 TranslateVar(798,SRpPGraphicNew);
 TranslateVar(799,SRpNoDataAvailableToPrint);
 TranslateVar(800,SRpPrintOnlyIfDataAvailable);
 TranslateVar(801,SRpPasswordConfirmationIncorrect);
 TranslateVar(802,SRpAAliasnameBeAssigned);
 TranslateVar(803,SRpAPathMustBeAssigned);
 TranslateVar(804,SRpAUserNameMustbeAssigned);
 TranslateVar(805,SRpUserorPasswordIncorrect);
 TranslateVar(814,SRpWindowsNTRequired);
 TranslateVar(815,SRpCannotExecute);
 TranslateVar(822,SRpServiceUnInstalled);
 TranslateVar(823,SRpServiceStopped);
 TranslateVar(824,SRpServiceStarted);
 TranslateVar(830,SRpSExternalpath);
 TranslateVar(831,SRpGetFieldValue);
 TranslateVar(832,SRpPGetFieldValue);
 TranslateVar(834,SRpChildSubRep);
 TranslateVar(859,SRpNewDatabaseInfo);
 TranslateVar(861,SRpSExternalData);
 TranslateVar(866,SRpExternalSectionNotFound);
 TranslateVar(867,SRpRecordnotExists);
 TranslateVar(868,SRpLoadSection);
 TranslateVar(879,SRpSInvalidJPEG);
 TranslateVar(880,SRpSJpegImages);
 TranslateVar(881,SRpSPNGImages);
 TranslateVar(882,SRpSXPMImages);
 TranslateVar(883,SRpSWMFImages);
 TranslateVar(884,SRpSEMFImages);
 TranslateVar(885,SRpSICOImages);
 TranslateVar(886,SRpSUnknownType);
 TranslateVar(887,SRpSFloat);
 TranslateVar(888,SRpSDate);
 TranslateVar(889,SRpSDateTime);
 TranslateVar(890,SRpSTime);
 TranslateVar(891,SRpSBoolean);
 TranslateVar(892,SRpSDataType);
 TranslateVar(893,SRpSChartDriverEngine);
 TranslateVar(894,SRpSChartDriverTeeChart);
 TranslateVar(67,SRpSDriver);

 TranslateVar(895,SRpChartLine);
 TranslateVar(897,SRpChartBar);
 TranslateVar(896,SRpChartPoint);
 TranslateVar(898,SRpChartHorzBar);
 TranslateVar(899,SRpChartArea);
 TranslateVar(900,SRpChartPie);
 TranslateVar(901,SRpChartArrow);
 TranslateVar(902,SRpChartBubble);
 TranslateVar(903,SRpChartGantt);
 TranslateVar(904,SRPSView3D);
 TranslateVar(905,SRPSView3DWalls);
 TranslateVar(906,SRPSPerspective);
 TranslateVar(907,SRPSElevation);
 TranslateVar(908,SRPSRotation);
 TranslateVar(909,SRPSOrthogonal);
 TranslateVar(910,SRPSZoom);
 TranslateVar(911,SRPSHOffset);
 TranslateVar(912,SRPSVOffset);
 TranslateVar(913,SRPSTilt);
 TranslateVar(914,SRPSMultibar);
 TranslateVar(915,SRpSNone);
 TranslateVar(916,SRpSSide);
 TranslateVar(917,SRpSStacked);
 TranslateVar(918,SRpSStacked100);
 TranslateVar(919,SRpSForcePrint);
 TranslateVar(920,SRpSHRelativeSkip);
 TranslateVar(921,SRpSVRelativeSkip);
 TranslateVar(922,SRpSHSkipExpre);
 TranslateVar(923,SRpSVSkipExpre);
 TranslateVar(924,SRpSSkipBefore);
 TranslateVar(925,SRpSSkipAfter);
 TranslateVar(926,SRpSSkipType);
 TranslateVar(927,SRpSSkipToPage);
 TranslateVar(928,SRpSPOnlyData);
 TranslateVar(929,SRpSTwoPassReportNeeded);
 TranslateVar(931,SRpNewDataInfo);
 TranslateVar(932,SRpPrintPDFRep9);
 TranslateVar(953,SRpFrench);
 TranslateVar(940,SRpIniNumPage);
 TranslateVar(941,SRpPrintNulls);
 TranslateVar(942,SrpSExpressionB);
 TranslateVar(943,SrpSExpressionA);
 TranslateVar(951,SRpSParamSubs);
 TranslateVar(954,SRpSRightToLeft);
 TranslateVar(955,SRpSBidiNo);
 TranslateVar(956,SRpSBidiPartial);
 TranslateVar(957,SRpSBidiFull);
 TranslateVar(958,SRpMultiPage);
 TranslateVar(959,SRpDataUnionNotFound);
 TranslateVar(960,SRpCannotCombine);
 TranslateVar(961,SRpSParamList);
 TranslateVar(962,SRpSParamListDesc);
 TranslateVar(963,SRpReplaceStr);
 TranslateVar(964,SRpPReplaceStr);
 TranslateVar(965,SRpParseParamsH);
 TranslateVar(966,SrpSClearExpChart);
 TranslateVar(967,SrpSBoolClearExp);
end;

{$IFDEF LINUX}
procedure RestoreEnviromentLocale;
var
 avalue:string;
begin
 avalue:=GetEnvironmentVariable('KYLIX_DEFINEDENVLOCALES');
 if Length(avalue)<1 then
  exit;
 avalue:=GetEnvironmentVariable('KYLIX_DECIMAL_SEPARATOR');
 if Length(avalue)>0 then
  DecimalSeparator:=avalue[1]
 else
  DecimalSeparator:=chr(0);
 avalue:=GetEnvironmentVariable('KYLIX_THOUSAND_SEPARATOR');
 if Length(avalue)>0 then
  ThousandSeparator:=avalue[1]
 else
  ThousandSeparator:=chr(0);
 avalue:=GetEnvironmentVariable('KYLIX_DATE_SEPARATOR');
 if Length(avalue)>0 then
  DateSeparator:=avalue[1]
 else
  DateSeparator:=chr(0);
 avalue:=GetEnvironmentVariable('KYLIX_TIME_SEPARATOR');
 if Length(avalue)>0 then
  TimeSeparator:=avalue[1]
 else
  TimeSeparator:=chr(0);
end;
{$ENDIF}

initialization

ConvertAllStrings;
{$IFDEF LINUX}
 RestoreEnviromentLocale;
{$ENDIF}
finalization
 if assigned(atrans) then
 begin
  atrans.free;
  atrans:=nil;
 end;
end.
