compo:
	cp ../../* .
	mkdir sample
	cp ../../test/clxreport/Unit1.* sample
	cp ../../test/clxreport/Project1.* sample
	cp ../repman/repsamples/sample4.rep sample
	cp ../repman/repsamples/biolife.cds sample

clean:
	-rm *.pas *.conf *.res *.dpk *.dcr *.conf *.dof *.kof *.ddp *.xfm *.dfm
	-rm -Rf sample
	-rm GNUmakefile~
	
