// Do not edit. This file is machine generated by the Resource DLL Wizard.

library metaview;

{$R *.RES}
{ITE} {LCID:00000409:00000C0A} {}
{ITE} {DFMFileType} {fmetaview.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdclitree.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdrepclient.xfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpprintdia.xfm}
{ITE} {RCFileType} {metaview_DRC.rc}

{$R 'fmetaview.xfm' FMeta:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdclitree.xfm' FRpCliTree:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdrepclient.xfm' modclient:TDataModule}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpprintdia.xfm' FRpPrintDialog:TForm}
{$R 'metaview_DRC.res' 'metaview_DRC.rc'}

{$E ESN}

begin
end.