kylix_bin=/opt/kylix3/bin

install:
	cp ../../repman/repmand .
	cp ../../repman/dbxdrivers .
	cp ../../repman/dbxconnections .
	cp ../../repman/utils/metaprint/metaprint .
	cp ../../repman/utils/metaview/metaview .
	cp ../../repman/utils/printrep/printrep .
	cp ../../repman/utils/reptotxt/reptotxt .
	cp ../../repman/utils/txttorep/txttorep .
	cp ../../repman/utils/printreptopdf/printreptopdf .
	-cp ../clxreport/Project1 .
	cp ../../repman/repsamples/sample4.rep .
	cp ../clxreport/biolife.cds .
	-mkdir doc
	cp ../../doc/doc/*.html doc
	mkdir doc/images
	cp ../../doc/doc/images/*.jpg doc/images
	tar c doc sample4.rep biolife.cds repmand dbxdrivers dbxconnections metaprint metaview printrep printreptopdf reptotxt txttorep repmand repmand.sh README > repmand-99g.i386.tar
	gzip repmand-99g.i386.tar
clean:
	-rm -f *.so *.so.1 *.so.2 *.so.1.0
	-rm -f repmand
	-rm -f dbxconnections dbxdrivers metaprint metaview printrep printreptopdf
	-rm -f reptotxt txttorep
	-rm -f *.gz
	-rm -f *.rep
	-rm -f *.cds
	-rm -Rf doc
	-rm *.rpmf
	-rm *.tar
	-rm *.pdf
