// Do not edit. This file is machine generated by the Resource DLL Wizard.

library repmandxp;

{$R *.RES}
{ITE} {LCID:00000409:00000C0A} {}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpdbxconfigvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpexpredlgvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpfparamsvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpgdidriver.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpgraphutilsvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfaboutvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdatainfovcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdesignvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfgridvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfmainvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfsampledatavcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfstrucvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdobjinspvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfigvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rppagesetupvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rprfvparams.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpvpreview.dfm}
{ITE} {RCFileType} {repmandxp_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpdbxconfigvcl.dfm' FRpDBXConfigVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpexpredlgvcl.dfm' FrpExpredialogVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpfparamsvcl.dfm' FRpParamsVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpgdidriver.dfm' FRpVCLProgress:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpgraphutilsvcl.dfm' FRpMessageDlgVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfaboutvcl.dfm' FRpAboutBoxVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdatainfovcl.dfm' FRpDatainfoconfigVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdesignvcl.dfm' FRpDesignFrameVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfgridvcl.dfm' FRpGridOptionsVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfmainvcl.dfm' FRpMainFVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfsampledatavcl.dfm' FRpShowSampledataVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfstrucvcl.dfm' FRpStructureVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdobjinspvcl.dfm' FRpObjInspVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfigvcl.dfm' FRpPrinterConfigVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rppagesetupvcl.dfm' FRpPageSetupVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rprfvparams.dfm' FRpRTParams:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpvpreview.dfm' FRpVPreview:TForm}
{$R 'repmandxp_DRC.res' 'repmandxp_DRC.rc'}

{$E ESN}

begin
end.