// Do not edit. This file is machine generated by the Resource DLL Wizard.

library repmandxp;

{$R *.RES}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpdbbrowservcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpdbxconfigvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpeditconnvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpexceldriver.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpexpredlgvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpfmainmetaviewvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpfmetaviewvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpfparamsvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpgdidriver.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpgraphutilsvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfaboutvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfconnectionvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdatasetsvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdatatextvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdesignvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdinfovcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfextsecvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfgridvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfmainvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfopenlibvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfsampledatavcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfsearchvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfstrucvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdftreevcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfwizardvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdobjinspvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdprintconfigvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdsysinfo.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rppagesetupvcl.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rprfvparams.dfm}
{ITE} {DFMFileType} {C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpvpreview.dfm}
{ITE} {RCFileType} {repmandxp_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpdbbrowservcl.dfm' FRpBrowserVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpdbxconfigvcl.dfm' FRpDBXConfigVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpeditconnvcl.dfm' FRpEditConVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpexceldriver.dfm' FRpExcelProgress:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpexpredlgvcl.dfm' FRpExpredialogVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpfmainmetaviewvcl.dfm' FRpMainMetaVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpfmetaviewvcl.dfm' FRpMetaVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpfparamsvcl.dfm' FRpParamsVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpgdidriver.dfm' FRpVCLProgress:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpgraphutilsvcl.dfm' FRpMessageDlgVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfaboutvcl.dfm' FRpAboutBoxVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfconnectionvcl.dfm' FRpConnectionVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdatasetsvcl.dfm' FRpDatasetsVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdatatextvcl.dfm' FRpDataTextVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdesignvcl.dfm' FRpDesignFrameVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfdinfovcl.dfm' FRpDInfoVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfextsecvcl.dfm' FRpExtSectionVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfgridvcl.dfm' FRpGridOptionsVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfmainvcl.dfm' FRpMainFVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfopenlibvcl.dfm' FRpOpenLibVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfsampledatavcl.dfm' FRpShowSampledataVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfsearchvcl.dfm' FRpSearchParamVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfstrucvcl.dfm' FRpStructureVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdftreevcl.dfm' FRpDBTreeVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdfwizardvcl.dfm' FRpWizardVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdobjinspvcl.dfm' FRpObjInspVCL:TFrame}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdprintconfigvcl.dfm' FRpPrinterConfigVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpmdsysinfo.dfm' FRpSysInfo:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rppagesetupvcl.dfm' FRpPageSetupVCL:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rprfvparams.dfm' FRpRTParams:TForm}
{$R 'C\PROG\TONI\CVSROOT\REPORTMAN\REPORTMAN\rpvpreview.dfm' FRpVPreview:TForm}
{$R 'repmandxp_DRC.res' 'repmandxp_DRC.rc'}

{$E ESN}

begin
end.