// Do not edit. This file is machine generated by the Resource DLL Wizard.

library repmand;

{$R *.RES}
{ITE} {LCID:00000409:00000C0A} {}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {reportman\rpgdidriver.dfm}
{ITE} {DFMFileType} {reportman\rprfvparams.dfm}
{ITE} {DFMFileType} {reportman\rpvpreview.dfm}
{ITE} {DFMFileType} {reportman\rpdbxconfig.xfm}
{ITE} {DFMFileType} {reportman\rpexpredlg.xfm}
{ITE} {DFMFileType} {reportman\rpfparams.xfm}
{ITE} {DFMFileType} {reportman\rpgraphutils.xfm}
{ITE} {DFMFileType} {reportman\rpmdfabout.xfm}
{ITE} {DFMFileType} {reportman\rpmdfdatainfo.xfm}
{ITE} {DFMFileType} {reportman\rpmdfdesign.xfm}
{ITE} {DFMFileType} {reportman\rpmdfgrid.xfm}
{ITE} {DFMFileType} {reportman\rpmdfhelpform.xfm}
{ITE} {DFMFileType} {reportman\rpmdfmain.xfm}
{ITE} {DFMFileType} {reportman\rpmdfsampledata.xfm}
{ITE} {DFMFileType} {reportman\rpmdfstruc.xfm}
{ITE} {DFMFileType} {reportman\rpmdobjinsp.xfm}
{ITE} {DFMFileType} {reportman\rppagesetup.xfm}
{ITE} {DFMFileType} {reportman\rppreview.xfm}
{ITE} {DFMFileType} {reportman\rpprintdia.xfm}
{ITE} {DFMFileType} {reportman\rpqtdriver.xfm}
{ITE} {DFMFileType} {reportman\rprfparams.xfm}
{ITE} {RCFileType} {repmand_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'reportman\rpgdidriver.dfm' FRpVCLProgress:TForm}
{$R 'reportman\rprfvparams.dfm' FRpRTParams:TForm}
{$R 'reportman\rpvpreview.dfm' FRpVPreview:TForm}
{$R 'reportman\rpdbxconfig.xfm' FRpDBXConfig:TForm}
{$R 'reportman\rpexpredlg.xfm' FrpExpredialog:TForm}
{$R 'reportman\rpfparams.xfm' FRpParams:TForm}
{$R 'reportman\rpgraphutils.xfm' FRpGraphProgres:TForm}
{$R 'reportman\rpmdfabout.xfm' FRpAboutBox:TForm}
{$R 'reportman\rpmdfdatainfo.xfm' FRpDatainfoconfig:TForm}
{$R 'reportman\rpmdfdesign.xfm' FRpDesignFrame:TFrame}
{$R 'reportman\rpmdfgrid.xfm' FRpGridOptions:TForm}
{$R 'reportman\rpmdfhelpform.xfm' FRpHelpForm:TForm}
{$R 'reportman\rpmdfmain.xfm' FRpMainF:TForm}
{$R 'reportman\rpmdfsampledata.xfm' FRpShowSampledata:TForm}
{$R 'reportman\rpmdfstruc.xfm' FRpStructure:TFrame}
{$R 'reportman\rpmdobjinsp.xfm' FRpObjInsp:TFrame}
{$R 'reportman\rppagesetup.xfm' FRpPageSetup:TForm}
{$R 'reportman\rppreview.xfm' FRpPreview:TForm}
{$R 'reportman\rpprintdia.xfm' FRpPrintDialog:TForm}
{$R 'reportman\rpqtdriver.xfm' FRpQtProgress:TForm}
{$R 'reportman\rprfparams.xfm' FRpRunTimeParams:TForm}
{$R 'repmand_DRC.res' 'repmand_DRC.rc'}

{$E ESN}

begin
end.