// Do not edit. This file is machine generated by the Resource DLL Wizard.

library repmandxp;

{$R *.RES}
{ITE} {LCID:00000C0A:00000C0A} {}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpdbbrowservcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpdbxconfigvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpeditconnvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpexceldriver.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpexpredlgvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpfmainmetaviewvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpfmetaviewvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpfparamsvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpgdidriver.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpgraphutilsvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfaboutvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfconnectionvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdatasetsvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdatatextvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdesignvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfdinfovcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfextsecvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfgridvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfmainvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfopenlibvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfsampledatavcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfstrucvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdftreevcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdfwizardvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdobjinspvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfigvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpmdsysinfo.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rppagesetupvcl.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rprfvparams.dfm}
{ITE} {DFMFileType} {C\prog\toni\cvsroot\reportman\reportman\rpvpreview.dfm}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {RCFileType} {repmandxp_DRC.rc}

{$R 'C\prog\toni\cvsroot\reportman\reportman\rpdbbrowservcl.dfm' FRpBrowserVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpdbxconfigvcl.dfm' FRpDBXConfigVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpeditconnvcl.dfm' FRpEditConVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpexceldriver.dfm' FRpExcelProgress:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpexpredlgvcl.dfm' FRpExpredialogVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpfmainmetaviewvcl.dfm' FRpMainMetaVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpfmetaviewvcl.dfm' FRpMetaVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpfparamsvcl.dfm' FRpParamsVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpgdidriver.dfm' FRpVCLProgress:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpgraphutilsvcl.dfm' FRpMessageDlgVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfaboutvcl.dfm' FRpAboutBoxVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfconnectionvcl.dfm' FRpConnectionVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdatasetsvcl.dfm' FRpDatasetsVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdatatextvcl.dfm' FRpDataTextVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdesignvcl.dfm' FRpDesignFrameVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfdinfovcl.dfm' FRpDInfoVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfextsecvcl.dfm' FRpExtSectionVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfgridvcl.dfm' FRpGridOptionsVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfmainvcl.dfm' FRpMainFVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfopenlibvcl.dfm' FRpOpenLibVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfsampledatavcl.dfm' FRpShowSampledataVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfstrucvcl.dfm' FRpStructureVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdftreevcl.dfm' FRpDBTreeVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdfwizardvcl.dfm' FRpWizardVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdobjinspvcl.dfm' FRpObjInspVCL:TFrame}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdprintconfigvcl.dfm' FRpPrinterConfigVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpmdsysinfo.dfm' FRpSysInfo:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rppagesetupvcl.dfm' FRpPageSetupVCL:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rprfvparams.dfm' FRpRTParams:TForm}
{$R 'C\prog\toni\cvsroot\reportman\reportman\rpvpreview.dfm' FRpVPreview:TForm}
{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'repmandxp_DRC.res' 'repmandxp_DRC.rc'}

{$E ESN}

begin
end.